### ISSUE TITLE
unsupported URL error for download from yfyf repo

### ISSUE THREAD

**Issue by Kyogre** [Paisseon/CyDownPlusPlus#1]
I am using Zebra v1.1.22.
If I try download tweak [arcfix](https://repo.yfyf.fun/index.php?method=view&pid=88) from https://repo.yfyf.fun/ I get error "unsupported URL". Disabling Cydown++ get the download works.
By the way same goes for original Cydown.

**Comment by Paisseon** [comment]
Unsupported URL means it's not on CyDown server, can't fix that.

**Comment by Paisseon** [comment]
Although I think that tweak is free so you might want to disable CyDown/++ for free tweaks
